version: '2'
services:
  #Mongo database
  mongo:
    image: 'mongo:3.6.2'
    volumes:
      - /tmp/data:/data/db
  #Theke
  theke:
    build: .
    ports:
      - "8090:80"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production